### ISSUE TITLE
ERROR:Failed to load the extension "more-translators".

### ISSUE THREAD

**Issue by swumagic** [Touch-Night/more-translators#2]
Traceback (most recent call last):
  File "D:\airj\text-generation-webui\text-generation-webui\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1
    import extensions.more-translators.script
                          ^
SyntaxError: invalid syntax

**Comment by Touch-Night** [comment]
Try rename the folder `more-translators` to `more_translators`

**Comment by swumagic** [comment]
TK YOU!
